import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { getAuthContext } from '@/lib/supabase/auth-helpers';
import { formatKES } from '@/lib/utils';

export async function GET(request: NextRequest) {
  try {
    const auth = await getAuthContext();
    if (!auth.success) return auth.response;

    const { searchParams } = new URL(request.url);
    const month = parseInt(searchParams.get('month') || String(new Date().getMonth() + 1));
    const year = parseInt(searchParams.get('year') || String(new Date().getFullYear()));

    const supabase = await createClient();
    const hid = auth.context.householdId;

    const startDate = `${year}-${String(month).padStart(2, '0')}-01`;
    const endDate =
      month === 12 ? `${year + 1}-01-01` : `${year}-${String(month + 1).padStart(2, '0')}-01`;

    const MONTH_NAMES = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ];

    // Get transactions for the month
    const { data: transactions } = await supabase
      .from('transactions')
      .select(
        'type, amount, date, description, merchant, categories(name), accounts!transactions_account_id_fkey(name)',
      )
      .eq('household_id', hid)
      .gte('date', startDate)
      .lt('date', endDate)
      .order('date', { ascending: true });

    const txns = transactions || [];
    const totalIncome = txns
      .filter((t) => t.type === 'income')
      .reduce((s, t) => s + Number(t.amount), 0);
    const totalExpenses = txns
      .filter((t) => t.type === 'expense')
      .reduce((s, t) => s + Number(t.amount), 0);

    // Get account balances
    const { data: accounts } = await supabase
      .from('accounts')
      .select('name, type, balance')
      .eq('household_id', hid)
      .eq('is_active', true);

    // Build HTML report (will be rendered as PDF by client)
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>FamFin Monthly Report — ${MONTH_NAMES[month - 1]} ${year}</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; color: #1a1a1a; }
    h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 8px; }
    h2 { color: #374151; margin-top: 24px; }
    .summary { display: flex; gap: 16px; margin: 16px 0; }
    .card { flex: 1; padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px; text-align: center; }
    .card .label { font-size: 12px; color: #6b7280; }
    .card .value { font-size: 20px; font-weight: bold; margin-top: 4px; }
    .income { color: #16a34a; }
    .expense { color: #dc2626; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 13px; }
    th { background: #f3f4f6; padding: 8px 12px; text-align: left; border-bottom: 2px solid #e5e7eb; }
    td { padding: 6px 12px; border-bottom: 1px solid #f3f4f6; }
    .right { text-align: right; }
    .footer { margin-top: 32px; font-size: 11px; color: #9ca3af; text-align: center; }
  </style>
</head>
<body>
  <h1>FamFin — Monthly Report</h1>
  <p><strong>${MONTH_NAMES[month - 1]} ${year}</strong></p>

  <div class="summary">
    <div class="card"><div class="label">Total Income</div><div class="value income">${formatKES(totalIncome)}</div></div>
    <div class="card"><div class="label">Total Expenses</div><div class="value expense">${formatKES(totalExpenses)}</div></div>
    <div class="card"><div class="label">Net</div><div class="value" style="color: ${totalIncome - totalExpenses >= 0 ? '#16a34a' : '#dc2626'}">${formatKES(totalIncome - totalExpenses)}</div></div>
  </div>

  <h2>Transactions (${txns.length})</h2>
  <table>
    <tr><th>Date</th><th>Description</th><th>Category</th><th>Account</th><th class="right">Amount</th></tr>
    ${txns
      .map((t) => {
        const cat = t.categories as { name: string } | null;
        const acc = t.accounts as { name: string } | null;
        return `<tr>
        <td>${t.date}</td>
        <td>${t.description || t.merchant || '—'}</td>
        <td>${cat?.name || '—'}</td>
        <td>${acc?.name || '—'}</td>
        <td class="right ${t.type === 'income' ? 'income' : 'expense'}">${t.type === 'income' ? '+' : '-'}${formatKES(Number(t.amount))}</td>
      </tr>`;
      })
      .join('')}
  </table>

  <h2>Account Balances</h2>
  <table>
    <tr><th>Account</th><th>Type</th><th class="right">Balance</th></tr>
    ${(accounts || []).map((a) => `<tr><td>${a.name}</td><td>${a.type}</td><td class="right">${formatKES(Number(a.balance))}</td></tr>`).join('')}
  </table>

  <div class="footer">
    Generated by FamFin on ${new Date().toLocaleDateString('en-GB')} — Confidential
  </div>
</body>
</html>`;

    return new NextResponse(html, {
      status: 200,
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `inline; filename="famfin-report-${MONTH_NAMES[month - 1]}-${year}.html"`,
      },
    });
  } catch {
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
