'use client';

import {
  Wallet,
  Banknote,
  Coins,
  CreditCard,
  PiggyBank,
  Landmark,
  CircleDollarSign,
  HandCoins,
  Receipt,
  Percent,
  TrendingUp,
  TrendingDown,
  BarChart3,
  ChartPie,
  ShoppingCart,
  ShoppingBag,
  Package,
  Store,
  Tag,
  Tags,
  Gift,
  Apple,
  Utensils,
  ChefHat,
  Coffee,
  Wine,
  Beer,
  Cake,
  Cookie,
  Salad,
  Egg,
  Sandwich,
  Pizza,
  IceCreamCone,
  Home,
  KeyRound,
  Sofa,
  Lamp,
  Hammer,
  Wrench,
  PaintBucket,
  Bed,
  Bath,
  DoorOpen,
  Car,
  CarTaxiFront,
  Bus,
  TrainFront,
  Plane,
  Bike,
  Fuel,
  MapPin,
  Navigation,
  Zap,
  PlugZap,
  Droplets,
  Wifi,
  Phone,
  Smartphone,
  Monitor,
  Tv,
  Radio,
  HeartPulse,
  Pill,
  Stethoscope,
  Syringe,
  Activity,
  Thermometer,
  GraduationCap,
  BookOpen,
  Library,
  Pencil,
  NotebookPen,
  School,
  Baby,
  Users,
  User,
  HandHeart,
  HeartHandshake,
  Film,
  Music,
  Gamepad2,
  Ticket,
  Drama,
  Palette,
  Camera,
  Headphones,
  Dumbbell,
  Trophy,
  Medal,
  Briefcase,
  Building,
  Building2,
  Laptop,
  Printer,
  Church,
  Heart,
  Globe,
  Luggage,
  Tent,
  Mountain,
  Palmtree,
  CircleDot,
  Star,
  Flag,
  Bookmark,
  FileText,
  Folder,
  Clock,
  Calendar,
  Bell,
  Shield,
  Lock,
  Eye,
  Search,
  Settings,
  Truck,
  Archive,
  type LucideIcon,
} from 'lucide-react';

export const ICON_MAP: Record<string, LucideIcon> = {
  wallet: Wallet,
  banknote: Banknote,
  coins: Coins,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  landmark: Landmark,
  'circle-dollar-sign': CircleDollarSign,
  'hand-coins': HandCoins,
  receipt: Receipt,
  percent: Percent,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'bar-chart-3': BarChart3,
  'chart-pie': ChartPie,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  package: Package,
  store: Store,
  tag: Tag,
  tags: Tags,
  gift: Gift,
  apple: Apple,
  utensils: Utensils,
  'chef-hat': ChefHat,
  coffee: Coffee,
  wine: Wine,
  beer: Beer,
  cake: Cake,
  cookie: Cookie,
  salad: Salad,
  egg: Egg,
  sandwich: Sandwich,
  pizza: Pizza,
  'ice-cream-cone': IceCreamCone,
  home: Home,
  'key-round': KeyRound,
  sofa: Sofa,
  lamp: Lamp,
  hammer: Hammer,
  wrench: Wrench,
  'paint-bucket': PaintBucket,
  bed: Bed,
  bath: Bath,
  'door-open': DoorOpen,
  car: Car,
  'car-taxi-front': CarTaxiFront,
  bus: Bus,
  'train-front': TrainFront,
  plane: Plane,
  bike: Bike,
  fuel: Fuel,
  'map-pin': MapPin,
  navigation: Navigation,
  zap: Zap,
  'plug-zap': PlugZap,
  droplets: Droplets,
  wifi: Wifi,
  phone: Phone,
  smartphone: Smartphone,
  monitor: Monitor,
  tv: Tv,
  radio: Radio,
  'heart-pulse': HeartPulse,
  pill: Pill,
  stethoscope: Stethoscope,
  syringe: Syringe,
  activity: Activity,
  thermometer: Thermometer,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  library: Library,
  pencil: Pencil,
  'notebook-pen': NotebookPen,
  school: School,
  baby: Baby,
  users: Users,
  user: User,
  'hand-heart': HandHeart,
  'heart-handshake': HeartHandshake,
  film: Film,
  music: Music,
  'gamepad-2': Gamepad2,
  ticket: Ticket,
  drama: Drama,
  palette: Palette,
  camera: Camera,
  headphones: Headphones,
  dumbbell: Dumbbell,
  trophy: Trophy,
  medal: Medal,
  briefcase: Briefcase,
  building: Building,
  'building-2': Building2,
  laptop: Laptop,
  printer: Printer,
  church: Church,
  heart: Heart,
  globe: Globe,
  luggage: Luggage,
  tent: Tent,
  mountain: Mountain,
  'palm-tree': Palmtree,
  'circle-dot': CircleDot,
  star: Star,
  flag: Flag,
  bookmark: Bookmark,
  'file-text': FileText,
  folder: Folder,
  clock: Clock,
  calendar: Calendar,
  bell: Bell,
  shield: Shield,
  lock: Lock,
  eye: Eye,
  search: Search,
  settings: Settings,
  truck: Truck,
  archive: Archive,
};

export const ICON_NAMES = Object.keys(ICON_MAP);

interface DynamicIconProps {
  name: string | null | undefined;
  className?: string;
}

export function DynamicIcon({ name, className = 'h-4 w-4' }: DynamicIconProps) {
  if (!name) return null;
  const Icon = ICON_MAP[name];
  if (!Icon) return null;
  return <Icon className={className} />;
}
